# Generated by Django 5.1.6 on 2025-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_remove_student_id_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
