# Generated by Django 4.2.16 on 2024-10-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
