# Generated by Django 4.2.16 on 2024-10-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
    ]
