# Generated by Django 5.1.6 on 2025-02-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_project_created_at_project_updated_at_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
