# Generated by Django 4.2.16 on 2024-10-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_institution_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemselection',
            options={'verbose_name': 'Probe Selection', 'verbose_name_plural': 'Probe Selections'},
        ),
    ]
