# Generated by Django 4.2.16 on 2024-10-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_problemselection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemselection',
            options={'verbose_name': 'Problem Selection', 'verbose_name_plural': 'Problem Selections'},
        ),
    ]
