# Generated by Django 4.2.16 on 2024-11-29 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_problemselection_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='student',
            name='notes',
        ),
        migrations.AddField(
            model_name='problemselection',
            name='problems',
            field=models.ManyToManyField(to='playground.problem'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(blank=True, max_length=400, null=True)),
                ('is_key', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, max_length=400, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.student')),
            ],
        ),
    ]
