# Generated by Django 4.2.16 on 2024-12-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_remove_problem_problems_remove_student_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='score_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source_type',
            field=models.CharField(blank=True, choices=[('translation', 'translation'), ('designed', 'designed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(blank=True, choices=[('input-integer', 'input-integer'), ('input-text', 'input-text'), ('multiple choice-text)', 'multiple choice-text'), ('multiple choice-image', 'multiple choice-image'), ('multiple selection-text', 'multiple selection-text'), ('multiple selection-image', 'multiple selection-image'), ('interactive', 'interactive')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
