# Generated by Django 4.2.16 on 2024-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_attempt_is_correct_attempt_score_attempt_score_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='text_choices',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
