# Generated by Django 4.2.16 on 2024-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_problem_text_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='text_choices',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
