# Generated by Django 4.2.16 on 2024-12-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_alter_problem_text_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='text_choices',
        ),
    ]
