# Generated by Django 4.2.16 on 2024-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_problem_text_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(blank=True, choices=[('input-integer', 'input-integer'), ('input-text', 'input-text'), ('multiple choice-text', 'multiple choice-text'), ('multiple choice-image', 'multiple choice-image'), ('multiple selection-text', 'multiple selection-text'), ('multiple selection-image', 'multiple selection-image'), ('interactive', 'interactive')], max_length=200, null=True),
        ),
    ]
