# Generated by Django 4.2.16 on 2024-12-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_alter_attempt_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
