# Generated by Django 4.2.16 on 2025-01-17 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_interactivechallenge_interactiveattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, max_length=400, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score_type', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interactiveattempt',
            name='attempt_ptr',
        ),
        migrations.RemoveField(
            model_name='interactiveattempt',
            name='challenge',
        ),
        migrations.AddField(
            model_name='interactivechallenge',
            name='note',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='topic_tags',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='InteractiveAttempt',
        ),
        migrations.AddField(
            model_name='problemattempt',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.problem'),
        ),
        migrations.AddField(
            model_name='problemattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
