# Generated by Django 4.2.16 on 2025-01-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0019_interactiveattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationBasedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('audience', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InteractiveAttempt',
        ),
        migrations.DeleteModel(
            name='InteractiveChallenge',
        ),
        migrations.AddField(
            model_name='station',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.stationbasedevent'),
        ),
        migrations.AddField(
            model_name='station',
            name='problems',
            field=models.ManyToManyField(to='playground.problem'),
        ),
    ]
