# Generated by Django 4.2.16 on 2025-01-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_station_stationbasedevent_delete_interactiveattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grades_and_difficulty', models.CharField(blank=True, max_length=200, null=True)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('topic_tags', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, max_length=400, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score_type', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.interactiveactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='activities',
            field=models.ManyToManyField(to='playground.interactiveactivity'),
        ),
    ]
