# Generated by Django 4.2.16 on 2025-01-17 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0021_interactiveactivity_interactiveattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_problem', models.BooleanField(blank=True, null=True)),
                ('student_answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('interactive_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.interactiveactivity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.problem')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.station')),
            ],
        ),
    ]
