# Generated by Django 4.2.16 on 2025-01-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0023_stationbasedevent_note_alter_eventattempt_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveactivity',
            name='html_file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stationbasedevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
