# Generated by Django 4.2.16 on 2025-01-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0024_interactiveactivity_html_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, to='playground.interactiveactivity'),
        ),
        migrations.AlterField(
            model_name='station',
            name='problems',
            field=models.ManyToManyField(blank=True, null=True, to='playground.problem'),
        ),
    ]
