# Generated by Django 4.2.16 on 2025-01-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0025_alter_station_activities_alter_station_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemattempt',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='InteractiveAttempt',
        ),
        migrations.DeleteModel(
            name='ProblemAttempt',
        ),
    ]
