# Generated by Django 4.2.16 on 2025-01-17 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0027_problemattempt_interactiveattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattempt',
            name='station',
        ),
        migrations.RemoveField(
            model_name='interactiveattempt',
            name='station',
        ),
        migrations.RemoveField(
            model_name='problemattempt',
            name='station',
        ),
        migrations.AlterField(
            model_name='eventattempt',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventattempt',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.problem'),
        ),
        migrations.AlterField(
            model_name='interactiveattempt',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.interactiveactivity'),
        ),
        migrations.AlterField(
            model_name='interactiveattempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problemattempt',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.problem'),
        ),
        migrations.AlterField(
            model_name='problemattempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
