# Generated by Django 4.2.16 on 2025-01-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0029_station_stationproblem_station_problems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='station',
            name='problems',
        ),
        migrations.CreateModel(
            name='StationInteractiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.interactiveactivity')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.station')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('station', 'activity')},
            },
        ),
    ]
