# Generated by Django 4.2.16 on 2025-01-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0030_remove_station_activities_remove_station_problems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, through='playground.StationInteractiveActivity', to='playground.interactiveactivity'),
        ),
        migrations.AddField(
            model_name='station',
            name='problems',
            field=models.ManyToManyField(blank=True, null=True, through='playground.StationProblem', to='playground.problem'),
        ),
    ]
