# Generated by Django 4.2.16 on 2025-01-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0031_station_activities_station_problems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='station',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
