# Generated by Django 4.2.16 on 2025-01-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0032_alter_station_options_station_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveactivity',
            name='index',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
